# Generated by Django 3.2.11 on 2022-01-27 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ['content']},
        ),
    ]
