# Generated by Django 4.0.1 on 2022-02-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_alter_quote_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='name_en',
        ),
        migrations.AddField(
            model_name='author',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='lang',
            field=models.CharField(choices=[('en', 'en'), ('ru', 'ru')], default='en', max_length=2),
            preserve_default=False,
        ),
    ]
